server {
    listen 80;
    server_name localhost;

    # 1. Arrel de fitxers ESTÀTICS (per a Nginx)
    # Aquesta és la teva carpeta ./frontend
    root /usr/share/nginx/html;
    index index.html;

    # 2. Servir fitxers estàtics (HTML, CSS, JS)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 3. Processar fitxers PHP
    location ~ \.php$ {
        # Incloure els paràmetres estàndard
        include fastcgi_params;
        fastcgi_pass   php:9000;
        fastcgi_param  SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
    }
}