server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    
    # Raíz para archivos estáticos (HTML, CSS, JS)
    root /usr/share/nginx/html;

    location / {
        # Intenta servir archivos estáticos, si no, pasa a index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # ❌ BORRAMOS o COMENTAMOS la línea try_files $uri =404;
        # Esto es vital porque los archivos PHP NO están en la carpeta de Nginx
        # try_files $uri =404; 

        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        
        # 👇 FORZAMOS LA RUTA DEL BACKEND 👇
        # Le decimos a PHP: "Oye, busca el archivo en TU carpeta /var/www/html"
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}